# Generated by Django 5.1.15 on 2026-10-08 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafeterias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_latitude', models.FloatField()),
                ('checkin_longitude', models.FloatField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='cafeterias.cafeteria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'cafeteria'), name='unique_user_cafeteria_visit')],
            },
        ),
    ]
