# Generated by Django 5.1.15 on 2026-10-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteria',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
